### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cwliu007** [brian-lau/MatlabR#3]
Hi Brian,

Thanks for providing this toolbox. 

1. In 'readme', it should be 'library(Rserve)', not 'library(RServe)'.

2.
How to resolve the error as follows?

>> r = MatR();
Warning: The following error was caught while executing 'MatR' class destructor:
Undefined function or variable 'RConnection'.

Error in MatR/kill (line 136)
         temp = RConnection();

Error in MatR/delete (line 129)
         self.kill(); 
Error using MatR/connect (line 37)
RServe java components not installed. Run setupMatR.

Error in MatR (line 20)
         self.connect();

**Comment by brian-lau** [comment]
Hi,

It seems like the Java components of Rserve have not been added to your path. The function `setupMatR` must be run in Matlab. I've updated the Readme to indicate this, and fix the typo you noted.
